_BASE_: "Base-C2-mask_L_R5021k_640b64_4x.yaml"
MODEL:
  ROI_BOX_HEAD:
    USE_ZEROSHOT_CLS: False
  ROI_HEADS:
    SEG_IN_FEATURE: 'p2'
  WEIGHTS: "DATASET/models/swin_large_patch4_window12_384_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: L-22k-384
    OUT_FEATURES: (0, 1, 2, 3)
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3"]
  REFINE_MASK:
    SEMANTIC_OUT_STRIDE: 4
SOLVER:
  MAX_ITER: 360000
  CHECKPOINT_PERIOD: 40000
  IMS_PER_BATCH: 16
  BASE_LR: 0.00005
INPUT:
  TRAIN_SIZE: 896